scania-digital-design-system/sdds-website

src/app/components/page/page.component.ts, src/app/data/templates.json
- Changed the data structure for templates to be more inline with what we expect in the future
=> Improve template setup

src/app/app.interface.ts, src/app/app.service.ts, src/app/components/main/main.component.ts, src/app/data/content.json
- Migrated all elements
- Moved docs data to service
- Added temporary docs interface (should be grabbed from stencil later on)
=> Migrated all elements

src/app/components/page/page.component.scss, src/app/data/content.json, src/app/data/templates.json
- Added component section
- added some styling to fix specific components e.g modal, progressbar
- Added a new template
=> adding bootstrap examples

README.md, angular.json, package-lock.json, package.json, src/404.html, src/app/app.module.ts, src/app/components/main/main.component.ts, src/index.html, src/main.ts
- Added 404 page for redirecting to angular route
- Added configuration to support running jekyll
=> Add GH-pages support

package-lock.json, package.json, src/app/app.interface.ts, src/app/app.service.ts, src/app/components/main/main.component.ts, src/app/components/navigation/navigation.component.ts, src/app/components/page/page.component.ts, src/app/data/templates.json
- Refactored all interfaces
- Added corporate ui and scania theme dependencies
=> Refactor interfaces

src/styles.scss
- Added missing global style for making scrolling possible
=> Fix scroll when default theme is used

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts, src/app/app.service.ts, src/app/components/note/note.component.html, src/app/components/note/note.component.scss, src/app/components/note/note.component.ts
- Created note component
- Added limitation note for IE users
=> Add a notification area

src/app/app.interface.ts, src/app/components/color-list/color-list.component.html, src/app/components/color-list/color-list.component.ts, src/app/components/icon-list/icon-list.component.ts, src/app/components/toggler/toggler.component.scss
- Added theme typing
- Styling fix for navigation in IE
=> Add theme typing

src/app/app.component.scss
- Changed nav item rule to be more specific
- Added overriding background color to fix issue with background rendering white color
=> Fix for IE navigation problem

src/app/app-routing.module.ts, src/app/app.interface.ts, src/app/components/main/main.component.ts, src/app/components/navigation/navigation.component.html, src/app/data/content.json, src/app/data/templates.json
- Changed data: page.items to be page.pages
- Made changes to interfaces, templates and controllers
=> Changed data structure and relations to it

src/index.html
- Store will load corporate-ui favicons
=> Remove angular favicon in corporate-ui-site 

package-lock.json, package.json
=> Bump version 4.0.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement-request.md
*Describe pull-request**  
- bug,improvement and feature templates added
Read the files and see if anything is missing
Similare to issue templates in scania-theme and corporate-ui
=> Added templates for issues

package-lock.json, package.json
Bump version corporate-ui and scania-theme
Look in package file
pre-release versions
=> Feature - Bump version corporate-ui and scania-theme

src/app/data/content.json
Added example for links in typography and updated icons
Read docs for icons and typography
=> Improvement - Added example for links in typography and updated icons

package-lock.json, package.json, src/app/components/icon-list/icon-list.component.scss, src/app/data/content.json
Bump versions of corporate-ui and scania-theme for site
Look at package and look at the site running
Added icons
=> Feature - Bump versions

package-lock.json, package.json
Bump version of corporate-ui and scania-theme
=> bump version 4.0.3 scania-theme 1.0.2

README.md, package.json
- Added faster way of creating links for scania-theme and corporate-ui
1. Run in corporate-ui and scania-theme
2. run `npm run link` command in corporate-ui-site
=> Improvement - Add script for local env

src/app/components/navigation/navigation.component.html, src/app/components/navigation/navigation.component.scss
- Added separation for external link
- Fix for bug in external link
=> Separation, style fix and bug fix for external link

src/app/components/page/page.component.scss
- Added image width and spacing
=> Added rule for images in colour page

src/app/components/page/page.component.scss
- Added flex layout and removed fixed height
=> Improved component listing

src/app/app-routing.module.ts, src/app/app.pipe.ts
=> Added sort pipe for overview page

package-lock.json, package.json, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/components/page/page.component.ts
- Added check for cookie before init analytics
- Added event listener for when cookie is created
- Added plugin for cookie handling
=> Added check for cookie before GA trigger

src/app/components/code-example/code-example.component.html, src/app/components/code-example/code-example.component.scss, src/app/components/code-example/code-example.component.ts, src/app/components/page/page.component.scss
- Matching the design for code-example now
- slight changes in the css for margin and padding
**Don't merge this until corporate-ui with code-example is released**
Go to component page and look at the code-example
=> Code example component updated

package-lock.json, package.json
Bump version for scania-theme and corporate-ui
=> Update corporate-ui and scania-theme

src/app/components/color-list/color-list.component.ts
- Literal regex is the only way supported by IE
=> Fix IE support for color list component

package-lock.json, package.json
Bump scania-theme
changed and updated package.json file
=> Bump scania-theme

src/app/components/page/page.component.ts
In IE the content didn't show up on the page when you visit the digitaldesign.scania.com. This because one of the methods used wasn't supported in IE. This PR remove that method and replace it with another solution for the unique filterning for the tabs. 
Fixes: #60 
1. **Run build**
2. **Run http-server** or something similare and visit IE
3. browse in the content and you should see it
old:
new: …
=> Small fix for the IE problem not showing content

fetchData.js, src/app/app-routing.module.ts, src/app/app.pipe.ts, src/app/components/page/page.component.scss
- Added last-modified information
- Added date formatter as a Pipe
- Use updated_at properties from data in template
How to test :
1. Add this to the template 'usage' text 
```
<p [innerHTML]='item.content.text | markdown | keepHtml'></p><p class='last-updated'>Last modified <span [innerHTML]='item.content.updated_at | dateFormat'></span></p>
```
2. Check one of article usage page
Notes: I will update template in SDDS CMS when this branch merged, to avoid error if data used in another branch (because new template content uses pipe)
=> Add timestamp

src/app/components/page/page.component.scss
- Added style for details, summary
- **For future development: support interactive click in IE**
=> Added style for FAQ page

src/app/components/page/page.component.ts
This is more of a clean up and some small refactor of the page.component
- Remove duplicated code
- Optimize the if statements
- making it more flexible
1. It will show the same content , but look at the code
2. somewhat faster load speed.
3. Making it more readable for the future
=> Refactor the page component in SDDS

src/app/app.component.html, src/app/data/content.json, src/app/data/navigation.json, src/app/data/templates.json
- Added FAQ pages & menu
- Added last modified information
- Remove 'Scania' from page title
=> Content-add new content faq & update page title

package-lock.json, package.json
=> bump data and version

src/app/components/code-example/code-example.component.html
- Remove the clutter in the code example page
Fixes: scania/corporate-ui#557
Run this pull-request with scania/corporate-ui#563
Look at the component section
related pull-request in scania/corporate-ui#563
=> Code example component bug

fetchData.js, src/app/components/code-example/code-example.component.html, src/app/components/page/page.component.ts
Add the possibility to add new section instead of one big rich text field from the cms.
Use this together with branch from cms scania/corporate-ui-cms#5
Needs my database and correct pr linked above
=> Section for the content added from cms 

package-lock.json, package.json, src/app/data/content.json, src/app/data/navigation.json, src/app/data/templates.json
- Update content
- Update corporate-ui
- Update scania-team
=> Update content and corporate ui package

src/404.html
Small fix regarding the issue endless redirecting loop, when running a http-server/netlify or similar. 
Fixes: #76 
SegmentCount = 1 made the pathname in correct which it redirected to an none existing page
1. Build and run a http-server
2. refresh and see if it enters an endless loop
or 
1. Go to this link on forked repo with netlify running 
2. https://goofy-murdock-5bba88.netlify.app/home refresh one time
Please run the angular enviroment also and check
=> Solving issue with redirect endless loop

src/app/components/main/main.component.ts
- Home was not shown after navigating to other pages
=> Fix bug in home URL

src/app/data/content.json
- Fix breadcrumbs link
- Added FAQ for bootstrap event
=> Added FAQ about bootstrap event

src/app/components/page/page.component.scss, src/app/data/content.json, src/app/data/navigation.json
Added a new color and background-color for the code part of getting started to make it easier to see
Get the latest content and look at the code parts of the getting started, should be scania black  for background and white for text color
This is temporary until we get more information how it should look like in the future
=> Add color fix for code section in getting started

README.md, package-lock.json, package.json
- Updated packages with latest scania-theme and corporate-ui version
- typo in readme
=> improvement - updated scania-theme and corporate-ui version

fetchData.js, src/app/app.interface.ts, src/app/components/code-example/code-example.component.html, src/app/components/code-props/code-props.component.ts, src/app/components/icon-list/icon-list.component.html, src/app/components/icon-list/icon-list.component.ts, src/app/components/page/page.component.html, src/app/components/page/page.component.scss, src/app/components/page/page.component.ts, src/app/components/page/tab-content/tab-content.component.html, src/app/components/page/tab-content/tab-content.component.ts
Update icon page templae
Part of
Fixes: #92 
1. Setup local strapi on this branch: https://github.com/scania/corporate-ui-cms/pull/16
2. Update database
3. Run corporate-ui-site with localhost (fetchData.js is pointing to localhost for now)
4. Check Icon Page following basic layout from Design
5. Check all pages is working with the new setup
Current view in Icon Page
In XD, it has line above icon-list, will be added in another PR as part of Icon List task.
=> Improvement - icon page main template

package-lock.json, package.json, src/app/data/content.json
update version and content data
Install corporate-ui and scania-theme
It should show the latest in the html attribute when running the site
=> Feature - Update version and content

package.json, src/app/app-routing.module.ts, src/app/components/icon-list/icon-list.component.html, src/app/components/icon-list/icon-list.component.scss, src/app/components/icon-list/icon-list.component.ts, src/app/components/page/page.component.scss, src/app/components/page/tab-content/tab-content.component.html
- When select all, check all boxes
- Add function to save selected items
- Added jszip helper to download icons as zip
- added check and uncheck icons function
- added category as input in icon-list component
- When download ongoing, add state in button
- Added color fallback for IE
Fixes: #104 
1. Check functionality to select & deselect icons
2. try download icons in zip
=> Icons page/select download icons

src/app/components/icon-list/icon-list.component.html, src/app/components/icon-list/icon-list.component.ts
- On search input, show filtered icons
Fixes: #104 
1. Use search function on icons page
2. Check if filter search works in all browsers
**Screenshots**
=> Icons page/Add search function

src/app/app.service.ts
To make it work with new store setup, change structure to follow stencil store
1. Link with corporate-ui https://github.com/scania/corporate-ui/pull/594
2. Try in all browsers
3. Should work in IE as well
=> Fix site to suit the new store setup

package-lock.json, src/app/app.component.scss, src/app/app.service.ts, src/app/components/color-list/color-list.component.scss, src/app/components/icon-list/icon-list.component.scss, src/app/components/main/main.component.scss, src/app/components/page/page.component.scss, src/app/data/content.json
4px base for site updated
You will need branch in scania-theme scania/scania-theme#162 and corporate-ui also scania/corporate-ui#595
Fixes: scania/scania-theme#158
Run site with all branches
=> Feature - 4px base for site updated

package-lock.json, package.json
Corporate-ui 4.2.0-1
Scania-theme 1.2.0-1
=> Add latest cui version

src/app/components/page/page.component.html
Remove fluid grid from the layout
- Max-width set
Fixes: #
Run the site
- Should have correct grid
- Max-width set on every breakpoint
=> Removed fluid grid

src/app/components/page/page.component.scss
=> temp fix for code bg

src/app/components/page/page.component.scss, src/app/components/page/tab-content/tab-content.component.html, src/app/data/content.json, src/app/data/navigation.json
Code snippet Styling added
Fixes: Look at the card in scania/projects
- Go to getting started > development > scroll to the bottom to see the correct example
- Look at figma
copy function is for later
=> code-snippet styling added

src/app/components/page/page.component.html, src/app/components/page/styles/anchor-menu.scss, src/app/components/page/styles/templates/do-dont.scss, src/app/components/page/tab-content/tab-content.component.html, src/app/data/content.json, src/app/data/navigation.json
- Using non fluid grid on the site
- Moved the anchor to align with design based on non fluid grid
- Changed breakpoint for anchor to lg
- Fixed bug for contribution page not showing cards/images mulit-columns
- Fixed code snippet added a spacing on first line
- Fixed full-size imaged columns
- Fixed colums for do and dont
- Centered the imaged in do and don'ts
- Go to spec pages 
- grid uses correctly
- Images full width fixed
- Contribution working
- Some tabs working again
=> Improvements - A lot of different fixes (grid,images,full width, do and donts)

src/app/app-vars.scss, src/app/components/page/page.component.html, src/app/components/page/styles/anchor-menu.scss, src/app/components/page/styles/templates/code.scss, src/app/components/page/tab-content/tab-content.component.html, src/app/components/page/tab-content/tab-content.component.ts, src/app/data/content.json
- position fixed
- Type-scale fixed
Based on feedback in #135 
- Anchor placement
- font-type on mobile vs desktop
- Figma design
=> Improvement - Fix for anchor position

src/app/components/card/card.component.scss, src/app/components/page/page.component.html, src/app/components/page/page.component.scss, src/app/components/page/styles/page-templates.scss, src/app/components/page/styles/templates/code.scss, src/app/components/page/styles/templates/images.scss, src/app/components/page/tab-content/tab-content.component.html, src/app/components/page/tab-content/tab-content.component.ts
- Added white space to break single \n from CMS in image caption
- Added link colour Fixes: #143
- Fix spacing of p element
- Fix image column sizing in multicolumns plugin Fix #147
- Added margin bottom to code example component Fix #151 Fix #144
- Added correct color and font for code inside body text
- Removed anchor menu from overview page #149
- Fix overview spacing Fix #149 
- Fix br not showing Fix #153
=> Fixes to styling (see description)

src/app/app.component.scss, src/app/app.module.ts, src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.scss, src/app/components/footer/footer.component.ts, src/app/components/main/main.component.html, src/app/components/main/main.component.scss, src/app/components/main/main.component.ts
Footer Added in main component
Fix #128 also
Fix #169 
Test in mobile and desktop
=> Add footer component

src/app/components/page/tab-content/tab-content.component.html, src/app/data/content.json, src/app/data/navigation.json
Fix for bug with multi column
Also solves issue with image sizes
for example in buttons the multi images had a different layout
Fixes: #177
go to buttons or an other component with multi images
=> Fix for bug with multi column

src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.scss, src/app/components/page/page.component.scss, src/app/components/page/styles/templates/images.scss
- Added footer padding back Fix #176 
- Fix ol li element spacing
=> Fix ol li and footer padding

src/index.html
- Added share link thumbnail
- Fix #174
=> Share link thumbnail

src/app/components/page/page.component.html
- Fix #168
- There was a condition to show content only if tab > 1, which is incorrect. Fixed that to >= 1
- Remove tab-pane class from BS that caused flex problem
=> Fix on first level nav page >> Contribution page

src/app/app.component.ts, src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.ts
Add link to footer content
Check if links in footer is added
=> Add footer from CMS

src/app/components/content-header/content-header.component.scss, src/app/components/header/header.component.scss
Fix so Scrollbar does not start below header logo
=> Fix scrolling behavior on the header and page

src/app/components/header/header.component.scss, src/app/data/content.json, src/app/data/navigation.json
=> move scania symbol temp

src/app/data/content.json, src/app/data/navigation.json
=> updated content

src/app/components/content-header/content-header.component.scss, src/app/components/footer/footer.component.html, src/app/components/page/landing-page/landing-page.component.html, src/app/components/page/page.component.scss
Add correct link to let us know button
Fix #193 
Fix #190
=> Add link to let us know button on landing page

src/app/app-routing.module.ts, src/app/components/page/styles/page-templates.scss, src/app/data/content.json, src/app/data/navigation.json
Fix for safari and router
Fixes: #
=> fix arrow for in safari

src/app/components/main/main.component.scss, src/app/components/page/styles/anchor-menu.scss
Fix #195 & Fix for sticky navbar on mobile
If anchor link not exist, do not add space there
See in mobile view for example this page https://digitaldesign.scania.com/resources/design
Compare the padding top between nav tab with Lead text
Should not be that big if anchor links does not exist
=> Fix for anchor menu

src/app/app.component.scss, src/app/components/main/main.component.html, src/app/components/main/main.component.scss, src/app/components/main/main.component.ts
- Fix #197
- On mobile view, display scroll to top button
- Added a small fix for nav left on mobile, when open, the height was not covering the whole screen on long screen (see image below). Added a fix for that.
=> Add scroll to top button

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement-request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, package-lock.json, package.json, src/app/app.interface.ts, src/app/components/code-props/code-props.component.ts, src/app/components/header/header.component.scss, src/app/components/icon-list/icon-list.component.ts, src/app/components/page/landing-page/landing-page.component.html, src/app/components/page/landing-page/landing-page.component.ts, src/app/components/page/page.component.html, src/app/components/page/page.component.scss, src/app/components/page/styles/page-templates.scss, src/app/data/content.json
- Fixing issue and PR templates
- Fixing reference to old corporate-ui
- Updated readme
- Try and download pictogram(Linking to new repo now for the download)
- Landing page had wrong columns on grid(Might need to remove the fluid talk with niklas regarding using fluid or not)
- Caption color
- Package.json
- Remove duplicate css from landing page
Fixes: #201 
Fixes: #165 
Also, but needs to discusses, fixes: #182
- Read the readme.md
- Read issues
- Look at site with image caption, correct color
- Look at the banner in bottom, related with …
=> Improvement - Updated references, Banner landingpage placement, readme update

src/app/components/icon-list/icon-list.component.ts
- Update link for icon download
=> Fix icon link github

src/app/data/content.json, src/app/data/navigation.json
=> New content update

package-lock.json, package.json, src/app/components/footer/footer.component.scss, src/app/components/icon-list/icon-list.component.html, src/app/components/icon-list/icon-list.component.scss, src/app/components/navigation/navigation.component.scss, src/app/components/page/styles/anchor-menu.scss, src/app/components/page/styles/tab-nav.scss, src/app/components/search-list/search-list.component.scss, src/app/data/content.json, src/app/data/navigation.json, src/tobedeprecated.scss
Fixes links in the site 
Fixes: part of #220 
=> Global styling added, fix some link css bug, content update

package.json, src/app/components/footer/footer.component.html, src/app/data/content.json
- update copyright 2021 in footer
- Update image in Components > Toggles
- Update version for release content update since last week
=> Added copyright 2021 and update image in toggle page

package-lock.json, package.json, src/app/components/icon-list/icon-list.component.html, src/app/components/icon-list/icon-list.component.scss, src/app/data/content.json, src/app/data/navigation.json
- Update content
- Textfield component added
- Package bump
Fixes: #206 #211 #208 #162 #226 
- Run preview
- Textfield component added in pictograms
=> Improvement - Update content, added textfield component 

src/app/data/content.json
=> Color content update

.github/workflows/azuredevops-issue.yml
=> Add issue as a task in azure

src/app/data/content.json
=> Update image size

fetchData.js, src/app/components/page/page.component.html, src/app/components/page/tab-content/tab-content.component.html
- Added sizing styling on the tab layout
- Update port for local CMS
Fix [AB#359](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/359)
- Test together with https://github.com/scania-digital-design-system/sdds-cms/pull/37 
- Run CMS on local
- Point fetchdata.js to local port
- Add some new size in do's and dont's
- Check how it looks like in the website
Design available here
SDDS UI › Page Templates & Specs › Do's & Don'ts
SDDS UI › UI Kit (SDDS) › Do Dont
=> AB#359 Update new size for dos and donts

src/app/components/page/styles/anchor-menu.scss, src/app/components/page/styles/tab-nav.scss, src/app/data/content.json
Updated the colors on anchor and navtabs from blue-900 --> grey-900
-- We no longer use any default blue as a text color
-- Pull down
-- Start 
**Screenshots**
=> Finished tasks, updated colors from blue to grey in anchor and nav

fetchData.js
Add new URL to fetch from AWS
Fixes: [AB#728](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/728)
- run npm run data
- Check if data fetched
One way to check if it correctly fetch new data, check on the image URL >> it changes from sdds-cms.s3 to cloudfront
- Check that all content is fine
=> AB#728 Update fetching url from Scania AWS

src/app/components/page/page.component.scss
-- Added spacing between "States" and "Default" to Textfield component in Styles tab
-- Fixes: [AB#573](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/573) #171 
-- Fixed: No spacing element was present
**Screenshots**
=> AB#573 Added spacing between in textfield Style -> States

package-lock.json, src/app/components/page/page.component.scss
- Remove link specific to site
- Let the site use link colour from Scania theme
- Update security dependency
- Fix #256 #255 #254 #248 #243 #237 [AB#802](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/802)
=> AB#802 Improvement/change link colour

src/app/components/code-example/code-example.component.scss
Header preview in the website, need to be positioned absolute
Fix [AB#855](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/855)
=> AB#855 Header styling for website

src/app/data/content.json
Update content
Fixes: [AB#947](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/947)
open netlify or run local
=> Update content and new grid running
